v = int(input('Vamos testar a tabuada de 1 até 10, diga um número:'))
print('-'*12)
print(f'{1:2} x {v} = {1*v}')
print(f'{2:2} x {v} = {2*v}')
print(f'{3:2} x {v} = {3*v}')
print(f'{4:2} x {v} = {4*v}')
print(f'{5:2} x {v} = {5*v}')
print(f'{6:2} x {v} = {6*v}')
print(f'{7:2} x {v} = {7*v}')
print(f'{8:2} x {v} = {8*v}')
print(f'{9:2} x {v} = {9*v}')
print(f'{10:2} x {v} = {10*v}')
print('-'*12)
